import { User } from "../../modules/uikit/pages/model/user.model";



export const dummyData: User[] = [
  {
    id: 1,
    name: 'John Doe',
    age: 30,
    username: 'johndoe',
    email: 'john.doe@example.com',
    phone: '+1-202-555-0156',
    website: 'johndoe.com',
    occupation: 'Software Engineer',
    hobbies: ['coding', 'hiking', 'reading'],
    status: 1,
    created_at: '2024-10-12T12:34:56Z',
  },
  {
    id: 2,
    name: 'Jane Smith',
    age: 25,
    username: 'janesmith',
    email: 'jane.smith@example.com',
    phone: '+1-202-555-0123',
    website: 'janesmith.net',
    occupation: 'Graphic Designer',
    hobbies: ['drawing', 'photography', 'travel'],
    status: 1,
    created_at: '2024-10-14T12:34:56Z',
  },
  {
    id: 3,
    name: 'Michael Brown',
    age: 35,
    username: 'michaelb',
    email: 'michael.brown@example.com',
    phone: '+1-202-555-0189',
    website: 'michaelbrown.me',
    occupation: 'Data Scientist',
    hobbies: ['data analysis', 'cycling', 'music'],
    status: 2,
    created_at: '2024-10-16T12:34:56Z',
  },
  {
    id: 4,
    name: 'Emily White',
    age: 28,
    username: 'emilyw',
    email: 'emily.white@example.com',
    phone: '+1-202-555-0147',
    website: 'emilywhite.org',
    occupation: 'Marketing Specialist',
    hobbies: ['writing', 'yoga', 'baking'],
    status: 2,
    created_at: '2024-10-18T12:34:56Z',
  },
  {
    id: 5,
    name: 'David Johnson',
    age: 40,
    username: 'davidj',
    email: 'david.johnson@example.com',
    phone: '+1-202-555-0168',
    website: 'davidjohnson.co',
    occupation: 'Product Manager',
    hobbies: ['innovation', 'gaming', 'finance'],
    status: 1,
    created_at: '2024-10-20T12:34:56Z',
  },
  {
    id: 6,
    name: 'Sarah Davis',
    age: 32,
    username: 'sarahd',
    email: 'sarah.davis@example.com',
    phone: '+1-202-555-0190',
    website: 'sarahdavis.dev',
    occupation: 'UI/UX Designer',
    hobbies: ['design', 'gardening', 'swimming'],
    status: 1,
    created_at: '2024-10-22T12:34:56Z',
  },
  {
    id: 7,
    name: 'Chris Lee',
    age: 29,
    username: 'chrislee',
    email: 'chris.lee@example.com',
    phone: '+1-202-555-0134',
    website: 'chrislee.io',
    occupation: 'Mobile Developer',
    hobbies: ['app development', 'traveling', 'reading'],
    status: 1,
    created_at: '2024-10-26T12:34:56Z',
  },
  {
    id: 8,
    name: 'Emma Wilson',
    age: 27,
    username: 'emmawilson',
    email: 'emma.wilson@example.com',
    phone: '+1-202-555-0175',
    website: 'emmawilson.tech',
    occupation: 'DevOps Engineer',
    hobbies: ['automation', 'gaming', 'blogging'],
    status: 3,
    created_at: '2024-10-28T12:34:56Z',
  },
  {
    id: 9,
    name: 'Sophia Martinez',
    age: 31,
    username: 'sophiam',
    email: 'sophia.martinez@example.com',
    phone: '+1-202-555-0191',
    website: 'sophiamartinez.dev',
    occupation: 'Frontend Developer',
    hobbies: ['painting', 'tech blogging', 'piano'],
    status: 2,
    created_at: '2024-10-30T12:34:56Z',
  },
  {
    id: 10,
    name: 'Liam Harris',
    age: 36,
    username: 'liamh',
    email: 'liam.harris@example.com',
    phone: '+1-202-555-0192',
    website: 'liamharris.dev',
    occupation: 'Backend Developer',
    hobbies: ['woodworking', 'gardening', 'cycling'],
    status: 1,
    created_at: '2024-11-01T12:34:56Z',
  },
  {
    id: 11,
    name: 'Olivia Walker',
    age: 29,
    username: 'oliviaw',
    email: 'olivia.walker@example.com',
    phone: '+1-202-555-0193',
    website: 'oliviawalker.dev',
    occupation: 'Digital Marketer',
    hobbies: ['photography', 'traveling', 'cooking'],
    status: 2,
    created_at: '2024-11-02T12:34:56Z',
  },
  {
    id: 12,
    name: 'Ethan Robinson',
    age: 33,
    username: 'ethanr',
    email: 'ethan.robinson@example.com',
    phone: '+1-202-555-0194',
    website: 'ethanrobinson.dev',
    occupation: 'Cloud Engineer',
    hobbies: ['gaming', 'photography', 'music'],
    status: 3,
    created_at: '2024-11-03T12:34:56Z',
  },
  {
    id: 13,
    name: 'Ava Hall',
    age: 28,
    username: 'avah',
    email: 'ava.hall@example.com',
    phone: '+1-202-555-0195',
    website: 'avahall.dev',
    occupation: 'SEO Specialist',
    hobbies: ['yoga', 'meditation', 'hiking'],
    status: 1,
    created_at: '2024-11-04T12:34:56Z',
  },
  {
    id: 14,
    name: 'Noah Allen',
    age: 38,
    username: 'noaha',
    email: 'noah.allen@example.com',
    phone: '+1-202-555-0196',
    website: 'noahallen.dev',
    occupation: 'Project Manager',
    hobbies: ['leadership', 'strategy games', 'traveling'],
    status: 2,
    created_at: '2024-11-05T12:34:56Z',
  },
  {
    id: 15,
    name: 'Isabella Carter',
    age: 27,
    username: 'isabellac',
    email: 'isabella.carter@example.com',
    phone: '+1-202-555-0197',
    website: 'isabellacarter.dev',
    occupation: 'Business Analyst',
    hobbies: ['reading', 'problem-solving', 'swimming'],
    status: 3,
    created_at: '2024-11-06T12:34:56Z',
  },
  {
    id: 16,
    name: 'James Scott',
    age: 34,
    username: 'jamess',
    email: 'james.scott@example.com',
    phone: '+1-202-555-0198',
    website: 'jamesscott.dev',
    occupation: 'System Architect',
    hobbies: ['designing systems', 'puzzles', 'chess'],
    status: 1,
    created_at: '2024-11-07T12:34:56Z',
  },
  {
    id: 17,
    name: 'Mia Thompson',
    age: 26,
    username: 'miat',
    email: 'mia.thompson@example.com',
    phone: '+1-202-555-0199',
    website: 'miathompson.dev',
    occupation: 'Recruiter',
    hobbies: ['networking', 'event planning', 'hiking'],
    status: 2,
    created_at: '2024-11-08T12:34:56Z',
  },
  {
    id: 18,
    name: 'William Moore',
    age: 37,
    username: 'williamm',
    email: 'william.moore@example.com',
    phone: '+1-202-555-0200',
    website: 'williamm.dev',
    occupation: 'Network Engineer',
    hobbies: ['building networks', 'programming', 'fishing'],
    status: 3,
    created_at: '2024-11-09T12:34:56Z',
  },
  {
    id: 19,
    name: 'Ella Rivera',
    age: 30,
    username: 'ellar',
    email: 'ella.rivera@example.com',
    phone: '+1-202-555-0201',
    website: 'ellarivera.dev',
    occupation: 'AI Researcher',
    hobbies: ['reading papers', 'coding', 'drawing'],
    status: 1,
    created_at: '2024-11-10T12:34:56Z',
  },
  {
    id: 20,
    name: 'Lucas Clark',
    age: 39,
    username: 'lucasc',
    email: 'lucas.clark@example.com',
    phone: '+1-202-555-0202',
    website: 'lucasclark.dev',
    occupation: 'Database Administrator',
    hobbies: ['optimizing queries', 'playing chess', 'photography'],
    status: 2,
    created_at: '2024-11-11T12:34:56Z',
  },
];
